INSERT INTO GENEROS(NOMBRE) VALUES ('Accion');
INSERT INTO GENEROS(NOMBRE) VALUES ('Comedia');
INSERT INTO GENEROS(NOMBRE) VALUES ('Drama');
INSERT INTO GENEROS(NOMBRE) VALUES ('Fantasia');
INSERT INTO GENEROS(NOMBRE) VALUES ('Terror');
INSERT INTO ACTORES(NOMBRE,URL_IMAGEN) VALUES('Hugh Jackman','https://pbs.twimg.com/profile_images/1618060433176383488/z6wO3CHz_400x400.jpg');
INSERT INTO ACTORES(NOMBRE,URL_IMAGEN) VALUES('Keanu Reeves','https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ8qpiVrthJOtOckTNcSG9-MCfchJDe4CKfd06QcjEZuZAONND0');